language: php

dist: xenial

services:
  - mysql
  - postgresql
  - xvfb

addons:
  apt:
    packages:
      - tidy
      - chromium-chromedriver
      - chromium-browser

env:
  global:
    - COMPOSER_ROOT_VERSION=4.x-dev
    - TRAVIS_NODE_VERSION="10"
    - DISPLAY=":99"
    - XVFBARGS=":99 -ac -screen 0 1024x768x16"
    - SS_BASE_URL="http://localhost:8080/"
    - SS_ENVIRONMENT_TYPE="dev"

matrix:
  include:
    - php: 7.1
      env: DB=PGSQL RECIPE_VERSION=4.7.x-dev PHPCS_TEST=1 PHPUNIT_TEST=1
    - php: 7.1
      env: DB=MYSQL RECIPE_VERSION=4.7.x-dev PHPUNIT_COVERAGE_TEST=1 PDO=1
    - php: 7.2
      env: DB=MYSQL RECIPE_VERSION=4.7.x-dev BEHAT_TEST=1
    - php: 7.3
      env: DB=MYSQL RECIPE_VERSION=4.7.x-dev NPM_TEST=1
    - php: 7.4
      env: DB=MYSQL RECIPE_VERSION=4.x-dev PHPUNIT_TEST=1

before_script:
  - sudo apt-get remove -y --purge google-chrome-stable || true

  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Install composer dependencies
  - composer validate
  - composer require silverstripe/recipe-cms:"$RECIPE_VERSION" silverstripe/recipe-testing:^1 --no-update
  - if [[ $BEHAT_TEST ]]; then composer require --no-update silverstripe/behat-extension:4.x-dev; fi;
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:^2 --no-update; fi
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

  # Remove once everything is merged
  - cd vendor/silverstripe/graphql
  - git checkout -t origin/master
  - cd ../admin
  - git remote add -f uc https://github.com/unclecheese/silverstripe-admin
  - git checkout pulls/1/schemageddon
  - cd ../../../
  ########################################################


  # Behat bootstrapping
  - if [[ $BEHAT_TEST ]]; then mkdir artifacts; fi
  - if [[ $BEHAT_TEST ]]; then cp composer.lock artifacts/; fi
  - if [[ $BEHAT_TEST ]]; then (chromedriver > artifacts/chromedriver.log 2>&1 &); fi
  - if [[ $BEHAT_TEST ]]; then (vendor/bin/serve --bootstrap-file vendor/silverstripe/cms/tests/behat/serve-bootstrap.php &> artifacts/serve.log &); fi

  # Install NPM dependencies
  - if [[ $NPM_TEST ]]; then nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION && npm install -g yarn && yarn install --network-concurrency 1 && (cd vendor/silverstripe/admin && yarn install --network-concurrency 1) && yarn run build; fi

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/ ; fi
  - if [[ $NPM_TEST ]]; then git diff-files --quiet -w --relative=client; fi
  - if [[ $NPM_TEST ]]; then git diff --name-status --relative=client; fi
  - if [[ $NPM_TEST ]]; then yarn run test; fi
  - if [[ $NPM_TEST ]]; then yarn run lint; fi
  - if [[ $BEHAT_TEST ]]; then vendor/bin/behat @silverstripe-elemental; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi

after_failure:
- php ./vendor/silverstripe/framework/tests/behat/travis-upload-artifacts.php --if-env BEHAT_TEST,ARTIFACTS_BUCKET,ARTIFACTS_KEY,ARTIFACTS_SECRET --target-path $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_BUCKET/ --artifacts-path ./artifacts/
