name: Merge-up

on:
  # At 12:20 PM UTC, only on Sunday
  schedule:
    - cron: '20 12 * * 0'
  workflow_dispatch:

jobs:
  merge-up:
    name: Merge-up
    # Only run cron on the silverstripe account
    if: (github.event_name == 'schedule' && github.repository_owner == 'silverstripe') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: Merge-up
        uses: silverstripe/gha-merge-up@v1
